# This is a basic workflow to help you get started with Actions

name: hg255d
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:

  build_openwrt:

    name: è‡ªåŠ¨ç¼–è¯‘hg255då›ºä»¶

    runs-on: ubuntu-16.04

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install g++ libncurses5-dev zlib1g-dev bison flex unzip autoconf gawk make gettext gcc binutils patch bzip2 libz-dev asciidoc subversion sphinxsearch libtool sphinx-common bash
          sudo -E apt-get clean
          sudo timedatectl set-timezone "Asia/Shanghai"
          df -h
          df -h

      - name: Compile hg255d
        run: |
          bash compile-action.sh

      - name: Prepare artifact
        run: |
          mkdir -p artifact/firmware
          ls -lh
          cp -rf $(find ./bin/ramips/ -type f -name "*sysupgrade.bin") ./artifact/firmware/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./artifact/firmware/

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"

      - name: Create release md
        run: |
          touch release.md
          echo "å›ºä»¶æž„å»ºæ—¥æœŸ${{ steps.tag.outputs.release_tag }}" > release.md
          echo "ä»¥ä¸‹ä¸ºå›½å†…ç”¨æˆ·åŠ é€Ÿä¸‹è½½åœ°å€ï¼Œä»»é€‰ä¸€" >> release.md
          echo "ðŸ”— [ç¾Žå›½çº¿è·¯åŠ é€Ÿä¸‹è½½1](https://gh.con.sh/https://github.com/teasiu/${{ github.event.repository.name }}/releases/download/${{ steps.tag.outputs.release_tag }}/openwrt-ramips-rt305x-hg255d-squashfs-sysupgrade.bin)" >> release.md
          echo "ðŸ”— [æ—¥æœ¬çº¿è·¯åŠ é€Ÿä¸‹è½½2](https://download.fastgit.org/teasiu/${{ github.event.repository.name }}/releases/download/${{ steps.tag.outputs.release_tag }}/openwrt-ramips-rt305x-hg255d-squashfs-sysupgrade.bin)" >> release.md
          echo "ðŸ”— [éŸ©å›½çº¿è·¯åŠ é€Ÿä¸‹è½½3](https://ghproxy.com/https://github.com/teasiu/${{ github.event.repository.name }}/releases/download/${{ steps.tag.outputs.release_tag }}/openwrt-ramips-rt305x-hg255d-squashfs-sysupgrade.bin)" >> release.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          release_name: ä¸‹è½½å›ºä»¶ ${{ steps.tag.outputs.release_tag }}
          body_path: release.md
          draft: false
          prerelease: false

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          
      - name: Upload firmware to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifact/firmware/openwrt-ramips-rt305x-hg255d-squashfs-sysupgrade.bin
          asset_name: openwrt-ramips-rt305x-hg255d-squashfs-sysupgrade.bin
          asset_content_type: application/bin

      - name: Upload release.md to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.md
          asset_name: release.md
          asset_content_type: application/md

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
